name = "MbedTLS"
uuid = "739be429-bea8-5141-9913-cc70e7f3736d"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "1.1.9"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
MbedTLS_jll = "c8ffd9c3-330d-5841-b78e-0817d7145fa1"
MozillaCACerts_jll = "14a3606d-f60d-562e-9121-12d972cd8159"
NetworkOptions = "ca575930-c2e3-43a9-ace4-1e988b2c1908"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"

[compat]
Dates = "1"
MbedTLS_jll = "2"
MozillaCACerts_jll = ">= 2020"
NetworkOptions = "1"
Random = "1"
Sockets = "1"
julia = "1.6"

[extras]
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Distributed"]
